print("From")
print("     Karishma,")
print("     HCAIHS,")
print("     Thoothukudi.")
print("                ")
print("To")
print("     Sakthi Computers,")
print("     Address,")
print("     Thoothukudi.")
print("                ")
print("Respected Sir")
print("   Subject:Reg. enquiry to join python class")
print("        Good morning sir.Since I have to attend a family function on April 1, I request that I want leave for 2 days.Kindly excuse my absence.")
print("                  Thanking you")
print("                                                                      Yours sincerely")
print("                                                                         Karishma.")